
#
#=
Examples for developing the JAC tools     
=#
println("A)  Tests & development of the electronic structure part.")
println("---------------------------------------------------------")
println("Aa) Test of the radial integration in CI computations (Randolf).")
println("Ab) Read in a full multiplet representation from files compatible to Ratip2012, Grasp2018, ....")
println("Ac) Test of several radial e-e potentials.")
println("Ad) Tests towards a SCF field: B-spline primitives and one-particle spectra in a local potential.")
println("Ae) Test of the CI part for an internally generated neon multiplet without Breit interaction.")
println("Af) Test of the frequency-independent Breit interaction for an internally generated neon multiplet.")
println("Ag) Test of the QED model corrections to the level structure of atoms and ions.")
println("Ah) Generate and normalize continuum orbitals in a local potential.")
println("Ai) Test of the jj-LS transformation of levels from a given multiplet.")
println("An) Test of a mean-field basis and configuration-interaction (CI) expansion.")
println("Ap) Test of restricted-active-space (RAS) expansion.")
println("Aq) Test of the Green(function) expansion.")
println("As) Test of spin-angular coefficients.")
println("At) Test of parallel computating with Julia.")
println("")
println("B)  Tests & development of atomic amplitudes")
println("--------------------------------------------")
println("Ba) Tests of the dipole, em multipole and momentum-transfer amplitudes.")
println("Bb) Tests of the parity non-conservation, Schiff moment and anapole moment amplitudes.")
println("")
println("C)   Tests & development of atomic properties")
println("---------------------------------------------")
println("Ca)  Test of the Einstein module with ASF from an internally generated multiplet.")
println("Cb)  Test of the Hfs module for HFS A,B parameters and hyperfine representation with ASF from an internally generated multiplet.")
println("Cc)  Test of the IsotopeShift module with ASF from an internally generated multiplet.")
println("Cde) Test of the LandeZeeman module with ASF from an internally generated multiplet.")
println("Cf)  Test of the FormFactor module with ASF from an internally generated multiplet.")
println("Cf)  Test of the FormFactor module with ASF from an internally generated multiplet.")
println("Cg)  Test of the reduced 1- and 2-particle density matrices & natural orbitals.")
println("Ch)  Test of the PlasmaShift module with ASF from an internally generated multiplet.")
println("Ci)  Test of the DecayYields module with ASF from an internally generated multiplet.")
#
println("Cxh)  Test of the AlphaVariation module with ASF from an internally generated multiplet.")
println("Cxk)  Test of the MultipolePolarizibility module with ASF from an internally generated multiplet.")
println("")
println("D)   Tests & development of atomic processes")
println("--------------------------------------------")
println("Da)  Test of the PhotoEmission module with ASF from an internally generated initial- and final-state multiplet.")
println("Db)  Test of the PhotoExcitation module with ASF from an internally generated initial- and final-state multiplet.")
println("Dc)  Test of the Photoionization module with ASF from an internally generated initial- and final-state multiplet.")
println("Dcp) Test of the Photoionization and PlasmaShift module with ASF from an internally generated initial- and final-state multiplet.")
println("Dd)  Test of the PhotoRecombination module with ASF from an internally generated initial- and final-state multiplet.")
println("De)  Test of the Auger module with ASF from an internally generated initial- and final-state multiplet.")
println("Dep) Test of the Auger and PlasmaShift modules with ASF from an internally generated initial- and final-state multiplet.")
println("Df)  Test of the Dielectronic module with ASF from an internally generated initial-, intermediate and final-state multiplets.")
println("Dg)  Test of the PhotoExcitationFluores module with ASF from an internally generated initial-, intermediate and final-state multiplets.")
println("Dh)  Test of the PhotoExcitationAutoIon module with ASF from an internally generated initial-, intermediate and final-state multiplets.")
println("Di)  Test of the RayleighCompton module with ASF from an internally generated initial- and final-state multiplets.")
println("Dj)  Test of the MultiPhotonDeExcitation module with ASF from an internally generated initial- and final-state multiplet.")
println("Dk)  Test of the CoulombExcitation module with ASF from an internally generated initial- and final-state multiplet.")
println("Dl)  Test of the PhotoIonizationFluores module with ASF from an internally generated initial-, intermediate and final-state multiplets.")
println("Dm)  Test of the PhotoIonizationAutoion module with ASF from an internally generated initial-, intermediate and final-state multiplets.")
println("Dn)  Test of the ImpactExcitation module with ASF from an internally generated initial- and final-state multiplet.")
println("Dp)  Test of the ImpactExcitationAutoion module with ASF from an internally generated initial-, intermediate and final-state multiplet.")
println("Dq)  Test of the RadiativeAuger module with ASF from an internally generated initial- and final-state multiplet.")
println("Dr)  Test of the MultiPhotonIonization module with ASF from an internally generated initial- and final-state multiplet.")
println("Ds)  Test of the MultiPhotonDoubleIon module with ASF from an internally generated initial- and final-state multiplet.")
println("Dt)  Test of the InternalConversion module with ASF from an internally generated initial- and final-state multiplet.")
println("Du) Test of the CoulombIonization module with ASF from an internally generated initial- and final-state multiplet.")
println("Dv) Test of the PairAnnihilation1Photon.jl module with ASF from an internally generated initial- and final-state multiplet.")
println("")
println("E)  Tests & development of atomic cascades")
println("------------------------------------------")
println("Ea) Three-step cascade after 1s-3p photo-excitation of Si^+: Configuration model.")
println("Eb) Simulation of the four-step cascade after 1s-3p photo-excitation of Si^+: Configuration model.")
println("Ec) Three-step cascade computations and simulations for the decay of the neon 1s^-1 3p hole states: AverageSCA model.")
println("Ed) Photoabsorption of Ne^+: AverageSCA model.")
println("")
println("F)  Tests & development of symbolic evaluations of Racah expressions")
println("--------------------------------------------------------------------")
println("Fa) Symbolic evaluation by means of special values & recursion relations of the Wigner n-j symbols.")
println("Fb) Symbolic simplification of Racah expressions by means of sum rules.")
println("Fc) Symbolic simplification of recoupling coefficients by means of sum rules.")
println("Fd) Symbolic simplification of Racah expressions including spherical harmonics and Wigner rotation matrices.")
println("Fe) Symbolic simplification of spherical tensor operators, matrix elements and spherical amplitudes.")
println("")
println("G)  Tests & development of semiempirical computations")
println("-----------------------------------------------------")
println("Ga) Tests of the semi-empirical computation of ADK rates.")
println("")
println("H)  Tests & development of atomic response computations")
println("-----------------------------------------------------")
println("Ha) Tests of the HighHarmonic module to calculate a high-harmonic spectrum in single-electron approximation.")
println("Hb) Tests of the StrongField module to calculate energy and momentum distributions of photoelectron in SFA.")

